# Generated by Django 5.1.6 on 2025-02-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=100)),
                ('application', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Planner', 'Planner')], max_length=50)),
                ('consent_text', models.TextField()),
                ('consent_pdf', models.FileField(blank=True, null=True, upload_to='consent_pdfs/')),
                ('provider_legal_name', models.CharField(max_length=255)),
                ('provider_trading_name', models.CharField(max_length=255)),
                ('provider_number', models.CharField(max_length=50)),
                ('provider_abn', models.CharField(max_length=50)),
                ('participant_full_name', models.CharField(max_length=255)),
                ('ndis_number', models.CharField(max_length=50)),
                ('service_categories', models.JSONField()),
                ('comments', models.TextField()),
                ('declaration', models.BooleanField(default=False)),
                ('signing_first_name', models.CharField(max_length=255)),
                ('signing_last_name', models.CharField(max_length=255)),
                ('signature', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
