# Generated by Django 5.1.6 on 2025-02-14 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_form', '0002_consentform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
